timeout: 2400s
steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '--file=./backend/Dockerfile.auth'
  - '--pull'
  - '--cache-from'
  - 'gcr.io/oursky-kube/presentation-microservices-kotlin-auth:latest'
  - '--tag'
  - 'gcr.io/oursky-kube/presentation-microservices-kotlin-auth:$SHORT_SHA'
  - '--tag'
  - 'gcr.io/oursky-kube/presentation-microservices-kotlin-auth:latest'
  - '--build-arg'
  - 'COMMIT_SHA=$COMMIT_SHA'
  - './backend'
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '--file=./backend/Dockerfile.app'
  - '--pull'
  - '--cache-from'
  - 'gcr.io/oursky-kube/presentation-microservices-kotlin-app:latest'
  - '--tag'
  - 'gcr.io/oursky-kube/presentation-microservices-kotlin-app:$SHORT_SHA'
  - '--tag'
  - 'gcr.io/oursky-kube/presentation-microservices-kotlin-app:latest'
  - '--build-arg'
  - 'COMMIT_SHA=$COMMIT_SHA'
  - './backend'
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '--file=./backend/Dockerfile.product'
    - '--pull'
    - '--cache-from'
    - 'gcr.io/oursky-kube/presentation-microservices-kotlin-product:latest'
    - '--tag'
    - 'gcr.io/oursky-kube/presentation-microservices-kotlin-product:$SHORT_SHA'
    - '--tag'
    - 'gcr.io/oursky-kube/presentation-microservices-kotlin-product:latest'
    - '--build-arg'
    - 'COMMIT_SHA=$COMMIT_SHA'
    - './backend'
images:
- 'gcr.io/oursky-kube/presentation-microservices-kotlin-auth:$SHORT_SHA'
- 'gcr.io/oursky-kube/presentation-microservices-kotlin-auth:latest'
- 'gcr.io/oursky-kube/presentation-microservices-kotlin-app:$SHORT_SHA'
- 'gcr.io/oursky-kube/presentation-microservices-kotlin-app:latest'
- 'gcr.io/oursky-kube/presentation-microservices-kotlin-product:$SHORT_SHA'
- 'gcr.io/oursky-kube/presentation-microservices-kotlin-product:latest'
